from .base import EmbeddingBase


class OrderEmbedding(EmbeddingBase):
    def __init__(self): ...

    def fit(self, data): ...


class FoodUserEmbedding(EmbeddingBase):
    def __init__(self): ...

    def fit(self, data): ...
