from .base import EmbeddingBase


class MovieEmbedding(EmbeddingBase):
    def __init__(self): ...

    def fit(self, data): ...


class MovieUserEmbedding(EmbeddingBase):
    def __init__(self): ...

    def fit(self, data): ...
