
input_data: data/ml-small-csv
device: cpu

# Env settings
state_size: 5
rating_threshold: 5
topk: 5
# embedding settings
user_embedding:
  name: dummy
  dim: 8

item_embedding:
  name: dummy
  dim: 8

drr:
  dim: 8

actor:
  hidden_dim : 64
  lr: 0.0001
  step_size: 50000

# critic config
critic:
  embedding_dim: 32
  hidden_dim: 64
  step_size: 50000
  lr: 0.0001

# MDP params
discount_factor: 0.9
replay_memory_size: 1000000
eps_priority: 1e-6
eps: 1.0
eps_decay: 0.000001
std: 1.5

# Training Settings
tau: 0.001
batch_size: 8
M: 20
workspace: workspace/test_0
